title: "Brennan Gillgrist Data Analytics Portfolio"
description: "A set of data analytics projects I have worked on so far:"
theme: jekyll-theme-minimal
nav:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects
  - title: "Resume"
    url: /assets/Resume.pdf
  - title: "LinkedIn"
    url: https://www.linkedin.com/in/your-linkedin-profile

profile_picture: /assets/DSC_0767.JPG
